package sql

import "fmt"

func GetMasterPD101(visitType string) string {
	s :=
		`
    SELECT
    DISTINCT NV.ACCOUNT_NO,
    NV.PRN,
    NV.VISIT_TYPE,
    TO_CHAR(NV.REGISTRATION_DATE,'YYYY-MM-DD') AS REGISTRATION_DATE ,
    NV.REGISTRATION_TIME,
    'N/A' AS CLUSTERFACILITYRN, 
    'N/A' AS ISPOLICECASE , 
    'N/A' AS LETTEROFGUARANTEE, 
    NVL (NV.REFERRER_CODE,'N/A') AS REFERRAL, -- nvl (b.gender,'N/A') AS JANTINA,
    NVL (PAT.TITLE,'N/A') AS TITLE,
    PAT.PATIENT_NAME,
    PAT.GENDER,
    TO_CHAR(PAT.DOB,'YYYY-MM-DD') AS DOB,
    --To_char(np.dob,'YYYY-MM-DD') AS dob,
    NVL (PAT.MARITAL_STATUS,'N/A') AS MARITAL_STATUS,
    NVL (PAT.RELIGION,'N/A') AS RELIGION,
    PAT.NATIONALITY,
    NVL (PAT.ETHNIC_GROUP,'N/A') AS ETHNIC_GROUP,
    NVL (PAT.OCCUPATION,'N/A') AS OCCUPATION,
    NVL (PAT.HEIGHT,'0 CM') AS HEIGHT,
    NVL (PAT.WEIGHT,'0 KG') AS WEIGHT,
    NVL (PAT.COUNTRY_OF_BIRTH,'N/A') AS COUNTRY_OF_BIRTH,
    'N/A' AS REFFOREIGNRCOUNTRYCODE, 
    'N/A' AS REFPERSONCATEGORYCODE,

    NVL ((SELECT DOCUMENT_TYPE FROM 
    (
        SELECT "REF_NO","PRN","DOCUMENT_TYPE","DOCUMENT_NUMBER","EXPIRY_DATE","CREATED_BY","CREATED_ON","SYNC_DATE","TRANSFER_FLG","TRANSFER_DATE_TIME","TRANSFER_SYSTEM","DOC_ID" from nova_patient_document_pd101 
        WHERE DOC_ID = '1'
    ) NPX_DOC_2_PD101 WHERE NPX_DOC_2_PD101.PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS DOCUMENT_TYPE,
    NVL ((SELECT DOCUMENT_NUMBER FROM 
    (
        select "REF_NO","PRN","DOCUMENT_TYPE","DOCUMENT_NUMBER","EXPIRY_DATE","CREATED_BY","CREATED_ON","SYNC_DATE","TRANSFER_FLG","TRANSFER_DATE_TIME","TRANSFER_SYSTEM","DOC_ID" from nova_patient_document_pd101 
        where doc_id = '1'
    ) NPY_DOC_2_PD101 WHERE NPY_DOC_2_PD101.PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS DOCUMENT_NUMBER,

    -- np.expiry_date,
    NVL (PAT.HOME_ADDRESS,'N/A') AS HOME_ADDRESS,
    NVL (PAT.ADDRESS1,'N/A') AS STREET1,
    NVL (PAT.ADDRESS2,'N/A') AS STREET2,
    NVL (PAT.ADDRESS3,'N/A') AS CITYCODE,
    NVL (PAT.ADDRESS4,'N/A') AS OCITY,
    NVL (PAT.ADDRESS5,'00000') AS POSTCODE,
    NVL (PAT.COUNTRY,'N/A') AS COUNTRY,

    NVL (PAT.HOME_PHONE, 'N/A') AS HOME_PHONE,
    NVL (PAT.MOBILE_PHONE, 'N/A') AS MOBILE_PHONE,
    NVL (NOK.TITLE, 'N/A') AS NOK_TITLE,
    NVL (NOK.PATIENT_NOK_NAME, 'N/A') AS PATIENT_NOK_NAME,
    NVL (NOK.RELATION_DESCRIPTION, 'N/A') AS RELATION_DESCRIPTION,
    --NVL (NOK.NOK_ID_TYPE, 'N/A') AS NOK_ID_TYPE,
    --NVL (NOK.NOK_ID, 'N/A') AS NOK_ID,
    -- Doc Type value based on MMC Prod
    NVL ((SELECT DOCUMENT_TYPE FROM NOVA_PATIENT_DOCUMENT WHERE PRN = NOK.NOK_ID AND DOCUMENT_TYPE IN ('NRIC/PP/BC', 'Passport', 'New IC') ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_ID_TYPE,
    NVL ((SELECT DOCUMENT_NUMBER FROM NOVA_PATIENT_DOCUMENT WHERE PRN = NOK.NOK_ID AND DOCUMENT_TYPE IN ('NRIC/PP/BC', 'Passport', 'New IC') ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_ID,

    NVL (NOK.HOME_ADDRESS, 'N/A') AS NOK_HOME_ADDRESS,
    NVL (NOK.MOBILE_PHONE, 'N/A') AS NOK_MOBILE_PHONE,
    NVL (NOK.HOME_PHONE, 'N/A') AS NOK_HOME_PHONE,
    REGISTRATION_DATE AS ADMISSION_DATE,
    --To_char(nv.admission_date,'YYYY-MM-DD') AS admission_date ,
    NV.REGISTRATION_TIME AS ADMISSION_TIME,
    --nv.admission_date,
    --nvl (nv.admission_time,'00:01') AS admission_time,
    NVL (NV.WARD_NO,'N/A') AS WARD_NO,
    NVL (NV.PRIMARY_SPECIALTY,'N/A') AS PRIMARY_SPECIALITY, -- REFSPECIALITYCODE, WRONG COLUMN NAMING IN SCHEMA
    NVL (NV.ADMISSION_STATUS,'N/A') AS ADMISSION_STATUS,
    NV.PAYMENT_CLASS_CODE,
    --nvl (To_char(nv.discharge_date,'DD/MM/YYYY'),'11/11/1900') AS discharge_date,
    --nvl (To_char(nv.discharge_date,'DD-MM-YYYY'),'11-11-1900') AS discharge_date,
    NVL (TO_CHAR(NV.DISCHARGE_DATE,'DD-MM-YYYY'), 'N/A') AS DISCHARGE_DATE,
    NVL (NV.DISCHARGE_TIME,'00:01') AS DISCHARGE_TIME,
    NV.CHARGE_CATEGORY_CODE,
    NVL (NV.DISCHARGE_REASON, 'N/A') AS DISCHARGE_REASON,
    --nvl (nv.discharge_date,'01/01/2099') AS discharge_date,
    --nv.discharge_time,
    --nvl (np.death_date,'01/01/2099') AS death_date,
    --DOC_CODE.DOCTOR_GRADE_CODE AS DISCHARGEOFFICERS,
    --'N/A' AS dischargeOfficers,
    NVL (NV.DISCHARGE_DOCTOR,'N/A') AS DISCHARGE_DOCTOR,-- NO INFO AT NOVA_PATIANT
    NVL (NV.MCR_NO,'N/A') AS MCR_NO

    FROM

    NOVA_PATIENT PAT,
    --nova_patient_document doc,
    --np_doc_2_PD101 doc,
    --nova_patient_nok nok,
    NOVA_PATIENT_NOK2 NOK,
    --(
    --    SELECT A.PATIENT_PRN, A.REF_NO, A.NOK_ID , A.NOK_ID_TYPE, A.RELATION_CODE, 
    --    A.RELATION_DESCRIPTION, A.PRN, A.RESIDENT_FLG, A.TITLE, A.PATIENT_NOK_NAME, 
    --    A.GENDER, A.MARITAL_STATUS, A.DOB, A.NATIONALITY, A.HOME_PHONE, 
    --    A.MOBILE_PHONE, A.HOME_ADDRESS, A.EMAIL
    --    FROM NOVA_PATIENT_NOK A, 
    --    (
    --        SELECT PATIENT_PRN, MAX(REF_NO) MREF --, title , patient_nok_name, relation_description, nok_id_type, nok_id, home_address, mobile_phone, home_phone 
    --        FROM  NOVA_PATIENT_NOK
    --        GROUP BY PATIENT_PRN
    --    ) B
    --    WHERE A.REF_NO = B.MREF
    --) NOK,
    NOVA_VISIT NV
    --(
    --    SELECT
    --    DISTINCT DOCTOR_GRADE_CODE,
    --    CASE
    --    WHEN TITLE IS NOT NULL 
    --    THEN (TITLE || ' ' || DOCTOR_NAME) 
    --    ELSE DOCTOR_NAME
    --    END AS doctor_title_name
    --  FROM NOVA_DOCTOR
    --) DOC_CODE

    WHERE
    PAT.PRN = NOK.PATIENT_PRN
    --and pat.prn = doc.prn (+)
    AND PAT.PRN = NV.PRN(+)
    AND NV.ADMISSION_DATE IS NOT NULL
    --and doc.document_type is not null
    --AND NV.DISCHARGE_DOCTOR = TRIM(DOC_CODE.DOCTOR_TITLE_NAME)
    AND NV.VISIT_TYPE IN %s
    AND NV.ADMISSION_DATE BETWEEN TO_DATE(:1, 'YYYY-MM-DD') AND TO_DATE(:2, 'YYYY-MM-DD')
    --and doc.document_type not in ('PRN-System Generated')
    --and doc.document_type in ('Birth Cert','Passport','NRIC/PP/BC','New IC')
    ORDER BY ADMISSION_DATE, ADMISSION_TIME
    `
	s = fmt.Sprintf(s, visitType)
    return s
}

func GetMasterPD301(visitType string) string {
    s :=
    `
    SELECT
    NV.ACCOUNT_NO,
    NP.PRN,
    TO_CHAR(NV.REGISTRATION_DATE,'YYYY-MM-DD') AS REGISTRATION_DATE,
    --To_char(nv.registration_date,'YYYY-MM-DD') AS registration_date,
    NV.VISIT_TYPE,
    NV.REGISTRATION_TIME,
    'N/A' AS CLUSTERFACILITYRN, 
    'N/A' AS ISPOLICECASE, 
    'N/A' AS LETTEROFGUARANTEE, 
    --nvl (nv.referrer_code,'N/A') AS referral, -- nvl (b.gender,'N/A') AS JANTINA,
    NVL (NV.REFERRER_CODE,'N/A') AS REFERRAL,
    NVL (NP.TITLE,'N/A') AS TITLE,
    NP.PATIENT_NAME,
    NP.GENDER,
    --np.dob,
    TO_CHAR(NP.DOB,'YYYY-MM-DD') AS DOB,
    NVL (NP.MARITAL_STATUS,'N/A') AS MARITAL_STATUS,
    NVL (NP.RELIGION,'N/A') AS RELIGION,
    NP.NATIONALITY,
    NVL (NP.ETHNIC_GROUP,'N/A') AS ETHNIC_GROUP,
    NVL (NP.OCCUPATION,'N/A') AS OCCUPATION,
    NVL (NP.HEIGHT,'0 CM') AS HEIGHT,
    NVL (NP.WEIGHT,'0 KG') AS WEIGHT,
    NVL (NP.COUNTRY_OF_BIRTH,'N/A') AS COUNTRY_OF_BIRTH,
    'N/A' AS REFFOREIGNRCOUNTRYCODE, 
    'N/A' AS REFPERSONCATEGORYCODE,
    NVL (NP.DOCUMENT_TYPE,'N/A') AS DOCUMENT_TYPE,
    NVL (NP.DOCUMENT_NUMBER,'N/A') AS DOCUMENT_NUMBER,
    -- np.expiry_date,
    NVL (NP.HOME_ADDRESS,'N/A') AS HOME_ADDRESS,
    NVL (NP.ADDRESS1,'N/A') AS STREET1,
    NVL (NP.ADDRESS2,'N/A') AS STREET2,
    NVL (NP.ADDRESS3,'N/A') AS CITYCODE,
    NVL (NP.ADDRESS4,'N/A') AS OCITY,
    NVL (NP.ADDRESS5,'00000') AS POSTCODE,
    NVL (NP.COUNTRY,'N/A') AS COUNTRY,

    NVL (NP.HOME_PHONE,'N/A') AS HOME_PHONE,
    NVL (NP.MOBILE_PHONE,'N/A') AS MOBILE_PHONE,
    NVL (NP.NOK_TITLE,'N/A') AS NOK_TITLE,
    NVL (NP.PATIENT_NOK_NAME,'N/A') AS PATIENT_NOK_NAME,
    NVL (NP.RELATION_DESCRIPTION,'N/A') AS RELATION_DESCRIPTION,
    --NVL (NP.NOK_ID_TYPE,'N/A') AS NOK_ID_TYPE,
    --NVL (NP.NOK_ID,'N/A') AS NOK_ID,
    -- Doc Type value based on MMC Prod
    NVL ((SELECT DOCUMENT_TYPE FROM NOVA_PATIENT_DOCUMENT WHERE PRN = NP.NOK_ID AND DOCUMENT_TYPE IN ('NRIC/PP/BC', 'Passport', 'New IC') ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_ID_TYPE,
    NVL ((SELECT DOCUMENT_NUMBER FROM NOVA_PATIENT_DOCUMENT WHERE PRN = NP.NOK_ID AND DOCUMENT_TYPE IN ('NRIC/PP/BC', 'Passport', 'New IC') ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_ID,

    NVL (NP.NOK_HOME_ADDRESS,'N/A') AS NOK_HOME_ADDRESS,
    NVL (NP.NOK_MOBILE_PHONE,'N/A') AS NOK_MOBILE_PHONE,
    NVL (NP.NOK_HOME_PHONE,'N/A') AS NOK_HOME_PHONE,
    --nv.admission_date,
    --nv.admission_time,
    NVL (NV.WARD_NO,'N/A') AS WARD_NO,
    --'N/A' AS primary_specialty,-- refSpecialityCode,
    NVL (NV.PRIMARY_SPECIALTY,'N/A') AS PRIMARY_SPECIALTY,
    NVL (NV.ADMISSION_STATUS,'N/A') AS ADMISSION_STATUS,
    NV.PAYMENT_CLASS_CODE,
    NV.CHARGE_CATEGORY_CODE,
    NVL (NV.DISCHARGE_REASON, 'N/A') AS DISCHARGE_REASON,
    --nvl (nv.discharge_date,'01/01/2099') AS discharge_date,
    --nv.discharge_time,
    --nvl (np.death_date,'01/01/2099') AS death_date,
    --'N/A' AS dischargeOfficers,
    --'N/A' AS discharge_doctor, -- no info at nova_patiant,
    --doc_code.doctor_grade_code AS dischargeOfficers,
    'N/A' AS DISCHARGEOFFICERS,
    NVL (NV.DISCHARGE_DOCTOR,'N/A') AS DISCHARGE_DOCTOR,
    NVL (NV.MCR_NO,'N/A') AS MCR_NO,
    NVL (NV.DIAGNOSIS_DESC,'N/A') AS DIAGNOSIS_DESC,
    --nvl (nv.description,'N/A') AS description, -- ICD9 issue
    'N/A' AS DESCRIPTION,
    TO_CHAR(NV.ADMISSION_DATE,'YYYY-MM-DD') AS ADMISSION_DATE,
    --nvl (To_char(nv.admission_date,'DD/MM/YYYY'),'11/11/2000') AS admission_date,
    NVL (NV.ADMISSION_TIME,'00:01') AS ADMISSION_TIME,
    NV.DISCHARGE_DATE,
    --To_char(nv.discharge_date,'YYYY-MM-DD') AS discharge_date,
    --nvl (To_char(nv.discharge_date,'DD/MM/YYYY'),'11/11/2000') AS discharge_date,
    NVL (NV.DISCHARGE_TIME,'00:01') AS DISCHARGE_TIME,
    NVL (NV.DIAGNOSIS_DESC,'N/A ()') AS ICD10_DESCRIPTION,
    NVL (NV.DIAGNOSIS_DESC,'N/A ()') AS ICD10_CODE
    --TO_DATE(admission_date, 'DD/MM/YYYY')

    FROM

    (
        SELECT 
        PAT.PRN,
        PAT.TITLE,
        PAT.PATIENT_NAME,
        PAT.GENDER,
        PAT.DOB,
        PAT.MARITAL_STATUS,
        PAT.RELIGION,
        PAT.NATIONALITY,
        PAT.ETHNIC_GROUP,
        PAT.OCCUPATION,
        PAT.HEIGHT,
        PAT.WEIGHT,
        PAT.COUNTRY_OF_BIRTH,

        (SELECT DOCUMENT_TYPE FROM 
        (
            SELECT "REF_NO","PRN","DOCUMENT_TYPE","DOCUMENT_NUMBER","EXPIRY_DATE","CREATED_BY","CREATED_ON","SYNC_DATE","TRANSFER_FLG","TRANSFER_DATE_TIME","TRANSFER_SYSTEM","DOC_ID" FROM NOVA_PATIENT_DOCUMENT_PD101 
            WHERE DOC_ID = '1'
        ) NP1_DOC_2_PD101 WHERE NP1_DOC_2_PD101.PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS DOCUMENT_TYPE,
        (SELECT DOCUMENT_NUMBER FROM 
        (
            SELECT "REF_NO","PRN","DOCUMENT_TYPE","DOCUMENT_NUMBER","EXPIRY_DATE","CREATED_BY","CREATED_ON","SYNC_DATE","TRANSFER_FLG","TRANSFER_DATE_TIME","TRANSFER_SYSTEM","DOC_ID" FROM NOVA_PATIENT_DOCUMENT_PD101 
            WHERE DOC_ID = '1'
        ) NP2_DOC_2_PD101 WHERE NP2_DOC_2_PD101.PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS DOCUMENT_NUMBER,
        (SELECT EXPIRY_DATE FROM 
        (
            SELECT "REF_NO","PRN","DOCUMENT_TYPE","DOCUMENT_NUMBER","EXPIRY_DATE","CREATED_BY","CREATED_ON","SYNC_DATE","TRANSFER_FLG","TRANSFER_DATE_TIME","TRANSFER_SYSTEM","DOC_ID" FROM NOVA_PATIENT_DOCUMENT_PD101 
            WHERE DOC_ID = '1'
        ) NP3_DOC_2_PD101 WHERE NP3_DOC_2_PD101.PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS EXPIRY_DATE,
        --doc.document_type,
        --doc.document_number,
        --doc.expiry_date,

        PAT.HOME_ADDRESS,
        PAT.ADDRESS1,
        PAT.ADDRESS2,
        PAT.ADDRESS3,
        PAT.ADDRESS4,
        PAT.ADDRESS5,
        PAT.COUNTRY,

        PAT.HOME_PHONE,
        PAT.MOBILE_PHONE,
        PAT.DEATH_DATE,

        NVL(NOK.TITLE, 'N/A') AS NOK_TITLE,
        NVL(NOK.PATIENT_NOK_NAME, 'N/A') AS PATIENT_NOK_NAME,
        NVL(NOK.RELATION_DESCRIPTION, 'N/A') AS RELATION_DESCRIPTION,
        NVL(NOK.NOK_ID_TYPE, 'N/A') AS NOK_ID_TYPE,
        NVL(NOK.NOK_ID, 'N/A') AS NOK_ID,
        NVL(NOK.HOME_ADDRESS, 'N/A') AS NOK_HOME_ADDRESS,
        NVL(NOK.MOBILE_PHONE, 'N/A') AS NOK_MOBILE_PHONE,
        NVL(NOK.HOME_PHONE, 'N/A') AS NOK_HOME_PHONE
        
        --nok.title AS nok_title,
        --nok.patient_nok_name,
        --nok.relation_description,
        --nok.nok_id_type,
        --nok.nok_id,
        --nok.home_address AS nok_home_address,
        --nok.mobile_phone AS nok_mobile_phone ,
        --nok.home_phone AS nok_home_phone

        FROM 
        NOVA_PATIENT PAT,
        NOVA_PATIENT_NOK2 NOK
        --nova_patient_document doc,
        --np_doc_2_PD101 doc,
        --nova_patient_nok nok
        WHERE 
        PAT.PRN = NOK.PATIENT_PRN(+)
        --and pat.prn = doc.prn (+)
        --order by prn
    ) NP,
    (
        SELECT 
        VISIT.PRN ,
        VISIT.ACCOUNT_NO,
        VISIT.VISIT_TYPE,
        VISIT.REGISTRATION_TIME,
        VISIT.REGISTRATION_DATE,
        VISIT.REFERRER_CODE,
        VISIT.ADMISSION_DATE,
        VISIT.ADMISSION_TIME,
        VISIT.ADMISSION_STATUS,
        VISIT.WARD_NO,
        VISIT.PAYMENT_CLASS_CODE,
        VISIT.CHARGE_CATEGORY_CODE,
        VISIT.DISCHARGE_REASON,
        VISIT.DISCHARGE_DATE,
        VISIT.DISCHARGE_TIME,
        VISIT.MCR_NO,
        VISIT.DISCHARGE_DOCTOR,
        NVL ((SELECT DIAGNOSIS_DESC FROM NOVA_PATIENT_DIAGNOSIS WHERE ACCOUNT_NO = VISIT.ACCOUNT_NO AND STATUS = 'FINALIZED' 
        AND PRIMARY_DIAGNOSIS = 'YES' ORDER BY DIAGNOSIS_REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS DIAGNOSIS_DESC,
        -- serv.description, CVSKL ; remove since ICD9 not info
        VISIT.PRIMARY_SPECIALTY

        FROM 
        NOVA_VISIT VISIT
        --nova_patient_diagnosis diag
        --nova_patient_services serv
        WHERE 
        --visit.account_no = diag.account_no (+)
        --and visit.account_no = serv.account_no (+) 
        VISIT.DISCHARGE_DATE IS NOT NULL
        --and diag.status = 'FINALIZED'
        --and diag.primary_diagnosis = 'YES'
        --order by account_no
    ) NV
    --DOC_GRADE_CODE doc_code

    WHERE
    NP.PRN = NV.PRN(+)
    AND REGISTRATION_DATE IS NOT NULL
    AND NV.VISIT_TYPE IN %s
    AND NV.DISCHARGE_DATE BETWEEN TO_DATE(:1, 'YYYY-MM-DD') AND TO_DATE(:2, 'YYYY-MM-DD')
    --AND NV.VISIT_TYPE IN ('INPATIENT')
    --AND NV.DISCHARGE_DATE BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD') AND TO_DATE('2021-09-17', 'YYYY-MM-DD')
    --and nv.discharge_doctor in (select distinct trim (doctor_title_name) from DOC_GRADE_CODE)
    --and doc_code.doctor_grade_code in ( select distinct doctor_grade_code from doc_grade_code where trim (doctor_title_name) = nv.discharge_doctor)
    --and np.document_type in ('NRIC/BIRTHCERT/PASSPORT')
    --and np.document_type in ('Birth Cert','Passport','NRIC/PP/BC','New IC')
    --and nv.discharge_doctor in (select distinct doctor_title_name from nova_doctor)
    ORDER BY ADMISSION_DATE, ADMISSION_TIME
    `
    s = fmt.Sprintf(s, visitType)
    return s
}

func GetMasterPD102() string {
    s :=
    `
    SELECT
    NV.ACCOUNT_NO,
    NP.PRN,
    NV.VISIT_TYPE,
    TO_CHAR(NV.REGISTRATION_DATE,'YYYY-MM-DD') AS REGISTRATION_DATE ,
    NV.REGISTRATION_TIME ,
    'N/A' AS ISPOLICECASE ,
    'N/A' AS INTERNALREFERRAL,
    NVL (NV.REFERRAL,'N/A') AS REFERRAL,
    NVL (NP.TITLE,'N/A') AS TITLE,
    NP.PATIENT_NAME,
    NP.GENDER,
    --np.dob,
    TO_CHAR(NP.DOB,'YYYY-MM-DD') AS DOB,
    NVL (NP.MARITAL_STATUS,'N/A') AS MARITAL_STATUS,
    NVL (NP.RELIGION,'N/A') AS RELIGION,
    NP.NATIONALITY,
    NVL (NP.ETHNIC_GROUP,'N/A') AS ETHNIC_GROUP,
    NVL (NP.COUNTRY_OF_BIRTH,'N/A') AS COUNTRY_OF_BIRTH,
    'N/A' AS REFFRCOUNTRYCODE,
    NVL (NP.DOCUMENT_TYPE,'N/A') AS DOCUMENT_TYPE,
    NVL (NP.DOCUMENT_NUMBER,'N/A') AS DOCUMENT_NUMBER,
    NVL (NP.HOME_ADDRESS,'N/A') AS HOME_ADDRESS,
    NVL (NP.ADDRESS1,'N/A') AS STREET1,
    NVL (NP.ADDRESS2,'N/A') AS STREET2,
    NVL (NP.ADDRESS3,'N/A') AS CITYCODE,
    NVL (NP.ADDRESS4,'N/A') AS OCITY,
    NVL (NP.ADDRESS5,'N/A') AS POSTCODE,
    NVL (NP.COUNTRY,'N/A') AS COUNTRY,
    
    'N/A' AS REFCOUNTRYCODE,
    'N/A' AS REFCONTACTTYPECODE,
    NVL (NP.HOME_PHONE,'N/A') AS HOME_PHONE,
    NVL (NP.MOBILE_PHONE,'N/A') AS MOBILE_PHONE,
    NVL (NP.HEIGHT, 'N/A') AS PERSON_HEIGHT,
    NVL (NP.WEIGHT, 'N/A') AS PERSON_WEIGHT,
    NVL (NP.PATIENT_NOK_NAME,'N/A') AS PATIENT_NOK_NAME,
    NVL (NP.RELATION_DESCRIPTION, 'N/A') AS RELATION_DESCRIPTION,
    'N/A' AS REFIDENTIFICATIONTYPECODE,
    'N/A' AS IDENTIFICATIONNO,
    NVL (NP.NOK_HOME_ADDRESS,'N/A') AS NOK_HOME_ADDRESS,
    'N/A' AS NOK_REFNOKCITYCODE,
    'N/A' AS NOK_REFNOKSTATECODE,
    'N/A' AS NOK_REFCOUNTRYCODE,
    'N/A' AS NOK_CONTACT_TYPE,
    NVL (NP.NOK_MOBILE_PHONE,'N/A') AS NOK_MOBILE_PHONE,
    NVL (NP.NOK_HOME_PHONE,'N/A') AS NOK_HOME_PHONE,
    'N/A' AS EMER_FULLNAME,
    'N/A' AS EMER_REFRELATIONSHIPCODE,
    'N/A' AS EMER_REFCONTACTTYPECODE,
    'N/A' AS EMER_CONTACTINFO,
    'N/A' AS REFWARDTRANSITIONTYPECODE,
    NVL (TO_CHAR(NV.ADMISSION_DATE,'DD/MM/YYYY'),'N/A') AS ADMISSION_DATE,
    NVL (NV.ADMISSION_TIME,'00:01') AS ADMISSION_TIME,
    NVL (NV.WARD_NO,'N/A') AS WARD_NO,
    'N/A' AS REFDISCIPLINECODE,
    NV.PAYMENT_CLASS_CODE,
    'N/A' AS REFWARDCATEGORYCODE,
    NV.GRAVIDA,
    NV.PARITY,
    NV.GESTATION_PERIOD,
    'N/A' AS ISMOTHERALIVE,
    'N/A' AS REFANTENATALCARECODE,
    NV.LABOUR_METHOD,
    'N/A' AS FATHERFULLNAME,
    'N/A' AS FATHERIDENTIFICATIONTYPECODE,
    'N/A' AS FATHERIDENTIFICATIONNO,
    'N/A' AS FATHERREFADDRESSTYPECODE,
    'N/A' AS FATHERSTREET1,
    'N/A' AS FATHERREFCOUNTRYCODE,
    'N/A' AS FATHERREFCONTACTTYPECODE,
    'N/A' AS FATHERCONTACTINFO,
    NV.DELIVERY_DATE,
    'N/A' AS BORNBEFOREARRIVAL,
    NV.RESULT_OF_BIRTH,
    'N/A' AS REFLABOURTYPECODE,
    NV.DELIVERY_TYPE,
    NV.CHILD_SEX,
    NV.WEIGHT,
    NV.LENGTH,
    'N/A' AS BIRTHHEADCIRCUMFERENCE,
    'N/A' AS REFBLOODTYPECODE,
    'N/A' AS REFRHESUSCODE,
    'N/A' AS REFMIN1APGARSCORECODE,
    'N/A' AS REFMIN5APGARSCORECODE,
    'N/A' AS REFLABOURCOMPLICATIONCODES,
    'N/A' AS BABYIDENTIFICATIONNO,
    'N/A' AS BABYREFIDENTIFICATIONTYPECODE,
    NV.FIRST_ASSISTED,
    'N/A' AS BABYREFLABOURATTENDANTTYPECODE,
    NV.DISCHARGE_DATE,
    NVL (NP.NOK_TITLE,'N/A') AS NOK_TITLE,
    --NVL (NP.NOK_ID_TYPE,'N/A') AS NOK_ID_TYPE,
    --NVL (NP.NOK_ID,'N/A') AS NOK_ID
    NVL ((SELECT DOCUMENT_TYPE FROM NOVA_PATIENT_DOCUMENT WHERE PRN = NP.NOK_ID AND DOCUMENT_TYPE IN ('NRIC/PP/BC', 'Passport', 'New IC') ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_ID_TYPE,
    NVL ((SELECT DOCUMENT_NUMBER FROM NOVA_PATIENT_DOCUMENT WHERE PRN = NP.NOK_ID AND DOCUMENT_TYPE IN ('NRIC/PP/BC', 'Passport', 'New IC') ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_ID

    FROM

    (
        SELECT 
        PAT.PRN,
        PAT.TITLE,
        PAT.PATIENT_NAME,
        PAT.GENDER,
        PAT.DOB,
        PAT.MARITAL_STATUS,
        PAT.RELIGION,
        PAT.NATIONALITY,
        PAT.ETHNIC_GROUP,
        PAT.OCCUPATION,
        PAT.HEIGHT,
        PAT.WEIGHT,
        PAT.COUNTRY_OF_BIRTH,

        (SELECT DOCUMENT_TYPE FROM 
        (
            SELECT "REF_NO","PRN","DOCUMENT_TYPE","DOCUMENT_NUMBER","EXPIRY_DATE","CREATED_BY","CREATED_ON","SYNC_DATE","TRANSFER_FLG","TRANSFER_DATE_TIME","TRANSFER_SYSTEM","DOC_ID" FROM NOVA_PATIENT_DOCUMENT_PD101 
            WHERE DOC_ID = '1'
        ) NP1_DOC_2_PD101 WHERE NP1_DOC_2_PD101.PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS DOCUMENT_TYPE,
        (SELECT DOCUMENT_NUMBER FROM 
        (
            SELECT "REF_NO","PRN","DOCUMENT_TYPE","DOCUMENT_NUMBER","EXPIRY_DATE","CREATED_BY","CREATED_ON","SYNC_DATE","TRANSFER_FLG","TRANSFER_DATE_TIME","TRANSFER_SYSTEM","DOC_ID" FROM NOVA_PATIENT_DOCUMENT_PD101 
            WHERE DOC_ID = '1'
        ) NP2_DOC_2_PD101 WHERE NP2_DOC_2_PD101.PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS DOCUMENT_NUMBER,
        (SELECT EXPIRY_DATE FROM 
        (
            SELECT "REF_NO","PRN","DOCUMENT_TYPE","DOCUMENT_NUMBER","EXPIRY_DATE","CREATED_BY","CREATED_ON","SYNC_DATE","TRANSFER_FLG","TRANSFER_DATE_TIME","TRANSFER_SYSTEM","DOC_ID" FROM NOVA_PATIENT_DOCUMENT_PD101 
            WHERE DOC_ID = '1'
        ) NP3_DOC_2_PD101 WHERE NP3_DOC_2_PD101.PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS EXPIRY_DATE,
        --doc.document_type,
        --doc.document_number,
        --doc.expiry_date,


        PAT.HOME_ADDRESS,
        PAT.ADDRESS1,
        PAT.ADDRESS2,
        PAT.ADDRESS3,
        PAT.ADDRESS4,
        PAT.ADDRESS5,
        PAT.COUNTRY,
        PAT.HOME_PHONE,
        PAT.MOBILE_PHONE,

        (SELECT TITLE FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS NOK_TITLE,
        (SELECT PATIENT_NOK_NAME FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS PATIENT_NOK_NAME,
        (SELECT RELATION_DESCRIPTION FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS RELATION_DESCRIPTION,
        (SELECT NOK_ID_TYPE FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS NOK_ID_TYPE,
        (SELECT NOK_ID FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS NOK_ID,
        (SELECT HOME_ADDRESS FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS NOK_HOME_ADDRESS,
        (SELECT MOBILE_PHONE FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS NOK_MOBILE_PHONE,
        (SELECT HOME_PHONE FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY) AS NOK_HOME_PHONE
        --nok.title AS nok_title,
        --nok.patient_nok_name,
        --nok.relation_description,
        --nok.nok_id_type,
        --nok.nok_id,
        --nok.home_address AS nok_home_address,
        --nok.mobile_phone AS nok_mobile_phone ,
        --nok.home_phone AS nok_home_phone

        FROM 
        NOVA_PATIENT PAT
        --nova_patient_document doc,
        --np_doc_2_PD101 doc,
        --nova_patient_nok nok
        --WHERE 
        --pat.prn = nok.patient_prn (+)
        --and pat.prn = doc.prn (+)
    ) NP,
    (
        SELECT 
        NV.ACCOUNT_NO,
        NV.PRN,
        NV.VISIT_TYPE,
        NV.REGISTRATION_DATE,
        NV.REGISTRATION_TIME,
        NV.REFERRAL,
        NV.CHARGE_CATEGORY_CODE,
        NV.ADMISSION_DATE,
        NV.ADMISSION_TIME,
        NV.WARD_NO,
        NV.PRIMARY_SPECIALTY,
        NV.PAYMENT_CLASS_CODE,
        NVL (TO_CHAR(NV.DISCHARGE_DATE,'DD/MM/YYYY'),'N/A') AS DISCHARGE_DATE,
        --nv.discharge_date,

        NVL (BR.GRAVIDA,'000') AS GRAVIDA,
        NVL (BR.PARITY,'00') AS PARITY,
        NVL (BR.GESTATION_PERIOD,'00') AS GESTATION_PERIOD,
        BR.LABOUR_METHOD,
        BR.DELIVERY_DATE,
        BR.RESULT_OF_BIRTH,
        BR.DELIVERY_TYPE,
        BR.CHILD_SEX,
        NVL (BR.WEIGHT,'0 KG') AS WEIGHT,
        --br.weight,
        NVL (BR.LENGTH,'0 CM') AS LENGTH,
        --br.length,
        BR.FIRST_ASSISTED

        FROM
        NOVA_VISIT NV,
        NOVA_BIRTH_DELIVERY BR

        WHERE
        (
            NV.ACCOUNT_NO IN
            (   SELECT DISTINCT ACCOUNT_NO FROM NOVA_BIRTH_DELIVERY
            )
        ) 
        AND NV.ACCOUNT_NO = BR.ACCOUNT_NO (+)
        AND NV.DISCHARGE_DATE IS NOT NULL
    ) NV

    WHERE 
    --np.document_type in ('Birth Cert','Passport','NRIC/PP/BC','New IC')
    NP.DOCUMENT_TYPE IS NOT NULL
    AND NP.GENDER = 'FEMALE' 
    AND NV.PRN = NP.PRN (+)
    AND NV.VISIT_TYPE = 'INPATIENT' 
    AND NV.DELIVERY_DATE BETWEEN TO_DATE(:1, 'YYYY-MM-DD') AND TO_DATE(:2, 'YYYY-MM-DD') 
    ORDER BY NV.ACCOUNT_NO ASC
    `
    return s
}

func GetMasterPD105() string {
    s :=
    `
    SELECT 
    DISTINCT PAT.PRN,
    NV.ACCOUNT_NO,
    NV.VISIT_TYPE,
    TO_CHAR(NV.REGISTRATION_DATE,'YYYY-MM-DD') AS REGISTRATION_DATE,
     NV.REGISTRATION_TIME,
    'N/A' AS ISPOLICECASE, 
    NVL (PAT.TITLE,'N/A') AS TITLE,
    PAT.PATIENT_NAME,
    PAT.GENDER,
    TO_CHAR(PAT.DOB,'YYYY-MM-DD') AS DOB,
    NVL (PAT.MARITAL_STATUS,'N/A') AS MARITAL_STATUS,
    NVL (PAT.RELIGION,'N/A') AS RELIGION,
    PAT.NATIONALITY,
    NVL (PAT.ETHNIC_GROUP,'N/A') AS ETHNIC_GROUP,
    NVL (PAT.OCCUPATION,'N/A') AS OCCUPATION,
    NVL (PAT.HEIGHT,'0 CM') AS HEIGHT,
    NVL (PAT.WEIGHT,'0 KG') AS WEIGHT,
    NVL (PAT.COUNTRY_OF_BIRTH,'N/A') AS COUNTRY_OF_BIRTH,
 
    NVL((SELECT DOCUMENT_TYPE FROM (SELECT DOCUMENT_TYPE FROM NOVA_PATIENT_DOCUMENT_PD101 WHERE PRN = PAT.PRN AND DOC_ID = 1 ORDER BY CREATED_ON DESC) WHERE ROWNUM = 1), 'N/A') AS DOCUMENT_TYPE,
    NVL((SELECT DOCUMENT_NUMBER FROM (SELECT DOCUMENT_NUMBER FROM NOVA_PATIENT_DOCUMENT_PD101 WHERE PRN = PAT.PRN AND DOC_ID = 1 ORDER BY CREATED_ON DESC) WHERE ROWNUM = 1), 'N/A') AS DOCUMENT_NUMBER,
    (SELECT EXPIRY_DATE FROM (SELECT EXPIRY_DATE FROM NOVA_PATIENT_DOCUMENT_PD101 WHERE PRN = PAT.PRN AND DOC_ID = 1 ORDER BY CREATED_ON DESC) WHERE ROWNUM = 1) AS EXPIRY_DATE,

    NVL (PAT.HOME_ADDRESS,'N/A') AS HOME_ADDRESS,
    NVL (PAT.ADDRESS1,'N/A') AS STREET1,
    NVL (PAT.ADDRESS2,'N/A') AS STREET2,
    NVL (PAT.ADDRESS3,'N/A') AS CITYCODE,
    NVL (PAT.ADDRESS4,'N/A') AS OCITY,
    NVL (PAT.ADDRESS5,'N/A') AS POSTCODE,
    NVL (PAT.COUNTRY,'N/A') AS COUNTRY,

    NVL (PAT.HOME_PHONE,'N/A') AS HOME_PHONE,
    NVL (PAT.MOBILE_PHONE,'N/A') AS MOBILE_PHONE,

    NVL ((SELECT TITLE FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_TITLE,
    NVL ((SELECT PATIENT_NOK_NAME FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS PATIENT_NOK_NAME,
    NVL ((SELECT RELATION_DESCRIPTION FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS RELATION_DESCRIPTION,

    NVL ((SELECT NOK_ID_TYPE FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN AND NOK_ID_TYPE IN ('New IC', 'NRIC/PP/BC') ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_ID_TYPE,
    NVL ((SELECT NOK_ID FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN AND NOK_ID_TYPE IN ('New IC', 'NRIC/PP/BC') ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_ID,

    NVL ((SELECT HOME_ADDRESS FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_HOME_ADDRESS,
    NVL ((SELECT MOBILE_PHONE FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_MOBILE_PHONE,
    NVL ((SELECT HOME_PHONE FROM NOVA_PATIENT_NOK WHERE PATIENT_PRN = PAT.PRN ORDER BY REF_NO DESC FETCH FIRST 1 ROWS ONLY), 'N/A') AS NOK_HOME_PHONE,

    TO_CHAR(NV.ADMISSION_DATE,'YYYY-MM-DD') AS ADMISSION_DATE,
    NVL (NV.ADMISSION_TIME,'00:01') AS ADMISSION_TIME,
    NVL (NV.WARD_NO,'N/A') AS WARD_NO,
    NVL (NV.PRIMARY_SPECIALTY,'N/A') AS PRIMARY_SPECIALTY,
    NVL (NV.ADMISSION_STATUS,'N/A') AS ADMISSION_STATUS,
    NV.PAYMENT_CLASS_CODE,
    PAT.DEATH_DATE

    FROM 

    NOVA_PATIENT PAT,
    PD105_NV NV
    WHERE 
    PAT.DEATH_DATE IS NOT NULL
    AND PAT.PRN = NV.PRN(+)
    AND (NV.PRN, NV.DISCHARGE_DATE) IN (
        SELECT PRN, MAX(DISCHARGE_DATE) FROM PD105_NV GROUP BY PRN
    )
	AND PAT.DEATH_DATE BETWEEN TO_DATE(:1, 'YYYY-MM-DD') AND TO_DATE(:2, 'YYYY-MM-DD') 
    ORDER BY PAT.DEATH_DATE ASC
    `
    return s
}
